[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.35"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 32, fail_on_revert = false }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
sort_imports = true
